ShopSphere/urls.py
from django.urls import path
from ShopSphere import views
from shop_sphere_project import settings
from django.conf.urls.static import static


app_name = 'ShopSphere'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'), 
    path('recommended/', views.recommended, name='recommended'),
    path('logout/', views.user_logout, name='logout'),
    
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('cart/', views.cart_detail, name='cart_detail'),
    path('cart/add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/remove/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('cart/clear/', views.clear_cart, name='clear_cart'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_sphere_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from ShopSphere import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name='index'),
    path('ShopSphere/', include('ShopSphere.urls')),
    # The above maps any URLs starting with ShopSphere/ to be handled by ShopSphere.
    path('admin/', admin.site.urls),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ShopSphere/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
    NAME_MAX_LENGTH = 128

    name = models.CharField(max_length=NAME_MAX_LENGTH, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Page(models.Model):
    TITLE_MAX_LENGTH = 128
    URL_MAX_LENGTH = 200

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title
    
class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # The additional attributes we wish to include.

    def __str__(self):
        return self.user.username

   
class Product(models.Model):
   category = models.CharField(max_length=255)
   name = models.CharField(max_length=255)
   description = models.TextField()
   price = models.DecimalField(max_digits=10, decimal_places=2)
   stock = models.PositiveIntegerField()
   image = models.ImageField(upload_to='product_images/', blank=True, null=True)
   def __str__(self):
       return self.name
   

class Cart(models.Model):
   user = models.OneToOneField(User, on_delete=models.CASCADE)
   created_at = models.DateTimeField(auto_now_add=True)
   def total_price(self):
       """Calculate total price of items in the cart"""
       return sum(item.total_price() for item in self.items.all())
   def total_items(self):
       """Total quantity of items in the cart"""
       return sum(item.quantity for item in self.items.all())
   
   
class CartItem(models.Model):
   cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name="items")
   product = models.ForeignKey(Product, on_delete=models.CASCADE)
   quantity = models.PositiveIntegerField(default=1)
   def total_price(self):
       """Calculate total price of this item"""
       return self.product.price * self.quantity
   
#class UserProfile(models.Model):
 #  user = models.OneToOneField(User, on_delete=models.CASCADE)
  # address = models.TextField(blank=True, null=True)
   #profile_image = models.ImageField(upload_to='profile_images/', blank=True)
   #def __str__(self):
    #   return self.user.username

ShopSphere/forms.py
from django import forms
from ShopSphere.models import Page, Category
from django.contrib.auth.models import User
from ShopSphere.models import UserProfile

from django import forms
from .models import Product
from django.contrib.auth.models import User


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=Category.NAME_MAX_LENGTH,
                            help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    # 10
    # 11 # An inline class to provide additional information on the form.
    class Meta:
        # 13 # Provide an association between the ModelForm and a model
        model = Category
        fields = ('name',)
    
class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=Page.TITLE_MAX_LENGTH,
                            help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=Page.URL_MAX_LENGTH,
                        help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    
    class Meta:
        # 25 # Provide an association between the ModelForm and a model
        model = Page

        # 28 # What fields do we want to include in our form?
        # 29 # This way we don't need every field in the model present.
        # 30 # Some fields may allow NULL values; we may not want to include them.
        # 31 # Here, we are hiding the foreign key.
        # 32 # we can either exclude the category field from the form,
        exclude = ('category',)
        # 34 # or specify the fields to include (don't include the category field).
        # 35 #fields = ('title', 'url', 'views')

        def clean(self):
            cleaned_data = self.cleaned_data
            url = cleaned_data.get('url')
            # If url is not empty and doesn't start with 'http://',
            # then prepend 'http://'.
            if url and not url.startswith('http://'):
                url = f'http://{url}'
                cleaned_data['url'] = url
            return cleaned_data
        
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class ProductForm(forms.ModelForm):
    
    class Meta:

        model = Product

        fields = ['category', 'name', 'description', 'price', 'stock', 'image'] 

ShopSphere/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from ShopSphere.models import Page
from ShopSphere.models import Category
from ShopSphere.forms import CategoryForm
from django.shortcuts import redirect
from ShopSphere.forms import PageForm
from django.urls import reverse
from ShopSphere.forms import UserForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from datetime import datetime

from .models import Product, Cart, CartItem
from .cart import Cart

def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]

    product_list = Product.objects.all()

    context_dict = {}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list

    context_dict['products'] = product_list
    
    response = render(request, 'ShopSphere/index.html', context=context_dict)
    return response


def product_detail(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    return render(request, 'ShopSphere/product_detail.html', {'product': product})

def cart_detail(request):
   """View the cart"""
   cart = Cart(request)
   return render(request, 'ShopSphere/cart_detail.html', {'cart': cart})

def add_to_cart(request, product_id):
   """Add a product to the cart"""
   product = get_object_or_404(Product, id=product_id)
   cart = Cart(request)
   cart.add(product)
   return redirect('ShopSphere:cart_detail')

def remove_from_cart(request, product_id):
   """Remove product from the cart"""
   product = get_object_or_404(Product, id=product_id)
   cart = Cart(request)
   cart.remove(product)
   return redirect('ShopSphere:cart_detail')

def clear_cart(request):
   """Clear all items from the cart"""
   cart = Cart(request)
   cart.clear()
   return redirect('ShopSphere:cart_detail')

def about(request):
    return render(request, 'ShopSphere/about.html')

def show_category(request, category_name_slug):
    # Create a context dictionary which we can pass
    # to the template rendering engine.
    context_dict = {}

    try:
        # Can we find a category name slug with the given name?
        # If we can't, the .get() method raises a DoesNotExist exception.
        # The .get() method returns one model instance or raises an exception.
        category = Category.objects.get(slug=category_name_slug)

        # Retrieve all of the associated pages.
        # The filter() will return a list of page objects or an empty list.
        pages = Page.objects.filter(category=category)

        # Adds our results list to the template context under name pages.
        context_dict['pages'] = pages
        # We also add the category object from
        # the database to the context dictionary.
        # We'll use this in the template to verify that the category exists.
        context_dict['category'] = category
    except Category.DoesNotExist:
        # We get here if we didn't find the specified category.
        # Don't do anything -
        # the template will display the "no category" message for us.
        context_dict['category'] = None
        context_dict['pages'] = None

    # Go render the response and return it to the client.
    return render(request, 'ShopSphere/category.html', context=context_dict)

@login_required
def add_category(request):
    form = CategoryForm()
    # A HTTP POST?
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        # Have we been provided with a valid form?
        if form.is_valid():
        # Save the new category to the database.
            form.save(commit=True)
            # Now that the category is saved, we could confirm this.
            # For now, just redirect the user back to the index view.
            return redirect('/ShopSphere/')
        else:
            # The supplied form contained errors -
            # just print them to the terminal.
            print(form.errors)
            # Will handle the bad form, new form, or no form supplied cases.
            # Render the form with error messages (if any).
    return render(request, 'ShopSphere/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None
    
    # You cannot add a page to a Category that does not exist...
    if category is None:
        return redirect('/ShopSphere/')
    
    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)
        
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                
                return redirect(reverse('ShopSphere:show_category',
                                kwargs={'category_name_slug':
                                category_name_slug}))
        else:
            print(form.errors)
    
    context_dict = {'form': form, 'category': category}
    return render(request, 'ShopSphere/add_page.html', context=context_dict)

def register(request):
    # A boolean value for telling the template
    # whether the registration was successful.
    # Set to False initially. Code changes value to
    # True when registration succeeds.
    registered = False

    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
    # Attempt to grab information from the raw form information.
    # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(request.POST)

        # If the two forms are valid...
        if user_form.is_valid():
        # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()
           
    # Update our variable to indicate that the template
    # registration was successful.
            registered = True
        else:
            # Invalid form or forms - mistakes or something else?
            # Print problems to the terminal.
            print(user_form.errors)
    else:
        # Not a HTTP POST, so we render our form using two ModelForm instances.
        # These forms will be blank, ready for user input.
        user_form = UserForm()
    

    # Render the template depending on the context.
    return render(request,
            'ShopSphere/register.html',
            context = {'user_form': user_form,
                        'registered': registered})

def user_login(request):
    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
        # We use request.POST.get('<variable>') as opposed
        # to request.POST['<variable>'], because the
        # request.POST.get('<variable>') returns None if the
        # value does not exist, while request.POST['<variable>']
        # will raise a KeyError exception.
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)
        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        if user:
        # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return redirect(reverse('ShopSphere:index'))
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your ShopSphere account is disabled.")
        else:
            # Bad login details were provided. So we can't log the user in.
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")
            # The request is not a HTTP POST, so display the login form.

    # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render(request, 'ShopSphere/login.html')

@login_required
def recommended(request):
    return render(request, 'ShopSphere/recommended.html')

# Use the login_required() decorator to ensure only those logged in can
# access the view.
@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)
    # Take the user back to the homepage.
    return redirect(reverse('ShopSphere:index'))

templates/ShopSphere/about.html
<!DOCTYPE html>
{% extends 'ShopSphere/base.html' %}
{% load staticfiles %} <!-- New line -->

<html>
    {% block title_block %}
        About ShopSphere
    {% endblock %}


    {% block body_block %}
        here is the about page.
        <div>
            <img src="{% static 'images/ShopSphere.jpg' %}" alt="Picture of ShopSphere" /> <!-- New line -->
        </div>
        <div>
            <img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat."/>
        </div>
    {% endblock %}

templates/ShopSphere/add_category.html
<!DOCTYPE html>
{% extends 'ShopSphere/base.html' %}

{% block title_block %}
    Add a Category
{% endblock %}
{% block body_block %}
    <form id="category_form" method="post" action="/ShopSphere/add_category/">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}
        <input type="submit" name="submit" value="Create Category" />
    </form>
{% endblock %}

templates/ShopSphere/add_page.html
<!DOCTYPE html>
{% extends 'ShopSphere/base.html' %}

{% block title_block %}
    Add a Page
{% endblock %}
{% block body_block %}
    <form id="add_page_form" method="post" action="{% url 'ShopSphere:add_page' category.slug %}">
        {% csrf_token %}
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}
        <input type="submit" name="submit" value="Add Page" />
    </form>
{% endblock %}

templates/ShopSphere/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load ShopSphere_template_tags %}

<html>
    <head lang="en">
        <meta charset="UTF-8" />
        <title>
            ShopSphere - 
            {% block title_block %}
            {% endblock %}
        </title>
    </head>
    <body>
        
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">ShopSphere</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'ShopSphere:index' %}">Home</a> 
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ShopSphere:recommended' %}">Recommended</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ShopSphere:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Recommended</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ShopSphere:register' %}">Sign Up</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ShopSphere:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ShopSphere:cart_detail' %}">Cart ({{ request.session.cart|length }})</a>
        </li>
        {% endif %}
        
      </ul>
      <form class="d-flex">
        <input class="form-control mx-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  
        <div>
            {% block body_block %}
            {% endblock %}

            {% block sidebar_block %}
                {% get_category_list category %}
            {% endblock %}
        </div>
            
        <hr />
        <div>
            <ul>
                {% if user.is_authenticated %}
                <!-- Show these links when the user is logged in -->
                <li><a href="{% url 'ShopSphere:recommended' %}">Recommended Page</a></li>
                <li><a href="{% url 'ShopSphere:logout' %}">Logout</a></li>
                <li><a href="{% url 'ShopSphere:add_category' %}">Add New Category</a></li>
                {% else %}
                <!-- Show these links when the user is NOT logged in -->
                <li><a href="{% url 'ShopSphere:register' %}">Sign Up</a></li>
                <li><a href="{% url 'ShopSphere:login' %}">Login</a></li>
                {% endif %}
                <!-- Outside the conditional statements, ALWAYS show -->
                <li><a href="{% url 'ShopSphere:about' %}">About</a></li>
                <li><a href="{% url 'ShopSphere:index' %}">Index</a></li>
            </ul>
        </div>
    </body>
</html>

templates/ShopSphere/cart_detail.html
{% extends 'ShopSphere/base.html' %}
{% load staticfiles %}
{% load ShopSphere_template_tags %}

{% block title_block %}
    ShopSphere Basket
{% endblock %}

{% block body_block %}

<h1>Your Shopping Cart</h1>
    {% if cart %}
    <ul>
        {% for item in cart %}

        <li>
        {{ item.name }} - £{{ item.price }} x {{ item.quantity }}
        <a href="{% url 'ShopSphere:remove_from_cart' item.id %}">Remove</a>
        </li>

        {% endfor %}
    </ul>
    <p>Total: £{{ cart.total_price }}</p>
    <a href="{% url 'ShopSphere:clear_cart' %}">Clear Cart</a>
    {% else %}
    <p>Your cart is empty.</p>
    {% endif %}
    <br><a href="{% url 'index' %}">Continue Shopping</a>

{%endblock%}

templates/ShopSphere/categories.html
<ul>
{% if categories %}
    {% for c in categories %}
        {% if c == current_category %}
        <li>
        <strong>
            <a href="{% url 'ShopSphere:show_category' c.slug %}">{{ c.name }}</a>
        </strong>
        </li>
        {% else %}
        <li>
            <a href="{% url 'ShopSphere:show_category' c.slug %}">{{ c.name }}</a>
        </li>
        {% endif %}
    {% endfor %}
{% else %}
    <li><strong>There are no categories present.</strong></li>
{% endif %}
</ul>
    

templates/ShopSphere/category.html
<!DOCTYPE html>
{% extends 'ShopSphere/base.html' %}
{% load staticfiles %}
{% load ShopSphere_template_tags %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>
    {% if pages %}
    <ul>
        {% for page in pages %}
        <li><a href="{{ page.url }}">{{ page.title }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
        <strong>No pages currently in category.</strong>
    {% endif %}
{% if user.is_authenticated %}
    <a href="{% url 'ShopSphere:add_page' category.slug %}">Add Page</a> <br />
{%else%}
    <strong>Login required to add a page</strong>
{%endif%}
    
    {% else %}
    The specified category does not exist.
    {% endif %}
{% endblock %}

templates/ShopSphere/index.html
<!DOCTYPE html>
{% extends 'ShopSphere/base.html' %}
{% load staticfiles %} 

{% block title_block %}
    Homepage
{% endblock %}

{% block body_block %}

    {% if user.is_authenticated %}
    howdy {{ user.username }}!
    {% else %}
    hey there partner!
    {% endif %}
    <br />
    <strong>{{ boldmessage }}</strong><br />

    
    {% if products %}
    <h2>Products</h2>
    <div class="products">
    <ul>
        {% for product in products %}
        <div class="product">
        <li>
            <h6>
                <a href="{% url 'ShopSphere:product_detail' product.id %}">Product: {{ product.name }}</a> 
            </h6>
            <a>{{ product.description }}</a>
            <a>Stock: {{ product.stock }}</a>
            <a>Price: £{{ product.price }}</a>

        </li>
        </div>
        {% endfor %}
    </ul>
    {%else%}
    <strong>There is no products present</strong>
    {% endif %}
    </div>

    <div>
    {%if categories %}
    <h2>Most Liked Categories</h2>
    <ul>
        {% for category in categories %}
            
            <!-- The following line is changed to add an HTML hyperlink -->
            <li>
                <a href="{% url 'ShopSphere:show_category' category.slug %}">
                {{ category.name }}
                </a>
            </li>
            
        {% endfor %}
    </ul>
    {% else %}
        <strong>There are no categories present.</strong>
    {% endif %}
    </div>
    <div>
    {% if pages %}
    <h2>Most Viewed Pages</h2>
        <ul>
        {% for page in pages %}
            <li><a href="{{ page.url }}">{{ page.title }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <strong>There are no pages present.</strong>
    {% endif %}


    </div>

    <div>
        <img src="{% static 'images/ShopSphere.jpg' %}" alt="Picture of ShopSphere" /> <!-- New line -->
    </div>
{% endblock %}

templates/ShopSphere/login.html
<!DOCTYPE html>
{% extends 'ShopSphere/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
    <h1>Login to ShopSphere</h1>
    <form id="login_form" method="post" action="{% url 'ShopSphere:login' %}">
            {% csrf_token %}
            Username: <input type="text" name="username" value="" size="50" />
            <br />
            Password: <input type="password" name="password" value="" size="50" />
            <br />
        <input type="submit" value="submit" />
    </form>
{% endblock %}

templates/ShopSphere/product_detail.html
<!DOCTYPE html>
{% extends 'ShopSphere/base.html' %}
{% load staticfiles %}
{% load ShopSphere_template_tags %}

{% block title_block %}
    {% if product %}
        {{ product.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
<h1>{{ product.name }}</h1>
   {% if product.image %}
<img src="{{ MEDIA_URL }}{{ product.image }}" alt="{{ product.name }}">
   {% else %}
<img src="{% static 'images/default-product-image.png' %}" alt="No image available">
   {% endif %}
<p>{{ product.description }}</p>
<p>Category: {{ product.category }}</p>
<p>Price: £{{ product.price }}</p>
<p>Stock: {{product.stock}}</p>
<a href="{% url 'ShopSphere:add_to_cart' product.id %}">Add to Cart</a>
<a href="{% url 'index' %}">Back to Home</a>

{%endblock%}

templates/ShopSphere/recommended.html
<!DOCTYPE html>
{% extends 'ShopSphere/base.html' %}

{% block title_block %}
    Recommended Page
{% endblock %}

{% block body_block %}
    Since you're logged in, you can see this text!
{% endblock %}

templates/ShopSphere/register.html
{% extends 'ShopSphere/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
    <h1>Register for ShopSphere</h1>
    {% if registered %}
        ShopSphere says: <strong>thank you for registering!</strong>
        <a href="{% url 'ShopSphere:index' %}">Return to the homepage.</a><br />

    {% else %}
        ShopSphere says: <strong>register here!</strong><br />
        <form id="user_form" method="post" action="{% url 'ShopSphere:register' %}"
            enctype="multipart/form-data">

            {% csrf_token %}

        <!-- Display each form -->

            {{ user_form.as_p }}
            {{ profile_form.as_p }}

        <!-- Provide a button to click to submit the form. -->
            <input type="submit" name="submit" value="Register" />
        </form>
    {% endif %}
{% endblock %}

templates/ShopSphere/restricted.html
<!DOCTYPE html>
{% extends 'ShopSphere/base.html' %}

{% block title_block %}
    Restricted Page
{% endblock %}

{% block body_block %}
    Since you're logged in, you can see this text!
{% endblock %}